// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WrapInDiv
{
    internal sealed partial class Vsix
    {
        public const string Id = "WrapInDiv.ec55e7ec-a66e-45d5-be7b-44f02cd2cd8c";
        public const string Name = "Wrap in DIV";
        public const string Description = @"Wraps a html div element around the selected text";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mensur Islami";
        public const string Tags = "";
    }
}
